services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - my_network

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - my_network

  app_pg:
    build: .
    volumes:
      - .:/app_pg
    working_dir: /app_pg
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  postgres_data:
  mongo_data:

networks:
  my_network: